url: https://ese.esiea.fr
baseurl: ""

# Site settings
title: ESIEA Secure Edition
email: ese@esiea.fr
description: "Conférences et ateliers sur la sécurité informatique et le hacking #ESE10"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/EsieaSecEdit
  - title: facebook
    url: https://www.facebook.com/esiea.secure.edition
  - title: linkedin
    url: https://www.linkedin.com/company/19056710

# Postal address (add as many lines as necessary)
address:
  - line: 9 rue de Vesale
  - line: 75005 Paris

# Build settings
markdown: kramdown
permalink: pretty
