title: ESIEA Secure Edition
description: > # this means to ignore newlines until "baseurl:"
  La conférence de cybersécurité par les étudiants de l'ESIEA
baseurl: "" # the subpath of your site, e.g. /blog
url: "esiea-secure-edition.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

logo: "../img/ese.png"

include: ['_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/ESIEASecEd
  - title: twitter
    url: https://twitter.com/EsieaSecEdit
  - title: linkedin
    url: https://www.linkedin.com/company/19056710

# Build settings
markdown: kramdown
permalink: pretty

