url: http://localhost:4000
baseurl: ""

# Site settings
title: ESIEA Secure Edition
email: ese@et.esiea.fr
description: "Conférences et ateliers sur la sécurité informatique et le hacking #ESE8"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/EsieaSecEdit
  - title: facebook
    url: https://www.facebook.com/ESIEASecEd
  - title: linkedin
    url: https://www.linkedin.com/company/19056710

# Postal address (add as many lines as necessary)
address:
  - line: 74 bis Avenue Maurice Thorez
  - line: 94200 Ivry-sur-Seine

# Build settings
markdown: kramdown
permalink: pretty
